version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./lms
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
