# https://fixmypc.ru/post/sozdanie-i-zapusk-konteinera-docker-s-django-postgressql-gunicorn-i-nginx/

version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build:
       context: ./lms
       dockerfile: Dockerfile
    # Запускаем сервер gunicorn - вместо python manage.py runserver 0.0.0.0:8000
    command: gunicorn lms.wsgi_prod:application --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/project/lms/static
      - media_volume:/home/project/lms/media
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev
    # Дожидаемся запуска контейнера db
    depends_on:
      - db

  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:12.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/project/lms/static
      - media_volume:/home/project/lms/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_volume:
  static_volume:
  media_volume: